/// Flutter icons Ecampus
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Ecampus
///      fonts:
///       - asset: fonts/Ecampus.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class Ecampus {
  Ecampus._();

  static const _kFontFam = 'Ecampus';

  static const IconData logo = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData forward = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xf0c9, fontFamily: _kFontFam);
  static const IconData newspaper = const IconData(0xf4f0, fontFamily: _kFontFam);
}
